# version: "3.7"
# services:
#   es01:
#     image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       node.name: es01
#       discovery.seed_hosts: es01,es02,es03
#       cluster.initial_master_nodes: es01,es02,es03
#       cluster.name: mycluster
#       bootstrap.memory_lock: "true"
#       ES_JAVA_OPTS: -Xms256m -Xmx256m
#     volumes:
#       - "es-data-es01:/usr/share/elasticsearch/data"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     healthcheck:
#       test: ["CMD-SHELL", "curl http://localhost:9200"]
#       interval: 10s
#       timeout: 10s
#       retries: 120
#   es02:
#     image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#     ports:
#       - "9201:9200"
#       - "9301:9300"
#     environment:
#       node.name: es02
#       discovery.seed_hosts: es01,es02,es03
#       cluster.initial_master_nodes: es01,es02,es03
#       cluster.name: mycluster
#       bootstrap.memory_lock: "true"
#       ES_JAVA_OPTS: -Xms256m -Xmx256m
#     volumes:
#       - "es-data-es02:/usr/share/elasticsearch/data"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     healthcheck:
#       test: ["CMD-SHELL", "curl http://localhost:9200"]
#       interval: 10s
#       timeout: 10s
#       retries: 120
#   es03:
#     image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
#     ports:
#       - "9202:9200"
#       - "9303:9300"
#     environment:
#       node.name: es03
#       discovery.seed_hosts: es01,es02,es03
#       cluster.initial_master_nodes: es01,es02,es03
#       cluster.name: mycluster
#       bootstrap.memory_lock: "true"
#       ES_JAVA_OPTS: -Xms256m -Xmx256m
#     volumes:
#       - "es-data-es03:/usr/share/elasticsearch/data"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     healthcheck:
#       test: ["CMD-SHELL", "curl http://localhost:9200"]
#       interval: 10s
#       timeout: 10s
#       retries: 120
#   kibana:
#     image: docker.elastic.co/kibana/kibana-oss:7.10.2
#     depends_on:
#       es01:
#         condition: service_healthy
#       es02:
#         condition: service_healthy
#       es03:
#         condition: service_healthy
#     ports:
#       - "5601:5601"
#     environment:
#       - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
# volumes:
#   es-data-es01:
#   es-data-es02:
#   es-data-es03:

version: "3.7"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es01
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  es02:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es02:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  es03:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9202:9200"
      - "9303:9300"
    environment:
      node.name: es03
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es03:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  flask-backend:
    build: ./flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - es01
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/"
      ELASTICSEARCH_URL: "http://es01:9200"
  nextjs-frontend:
    build: ./iso-electron
    ports:
      - "3000:3000"
    depends_on:
      - flask-backend
volumes:
  es-data-es01:
  es-data-es02:
  es-data-es03:
  mongo-data:
