import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className + ' flex items-center justify-center'}>
        <div className='md:block hidden md:w-3/12 bg-slate-900'>
          görkem karamolla
        </div>
        <div className='w-full md:w-6/12'>{children}</div>
        <div className='md:block hidden  md:w-3/12 bg-slate-900'>
          görkem karamolla
        </div>
      </body>
    </html>
  );
}
