version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: your_mongo_db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      MONGO_DB_URI: "mongodb://root:example@mongodb:27017/your_mongo_db?authSource=admin"
      MONGO_DB_NAME: "your_mongo_db"
      ES_HOST: "http://elasticsearch:9200"
    depends_on:
      - mongodb
      - elasticsearch
